### ISSUE TITLE
Redux for two window

### ISSUE THREAD

**Issue by Ruslan27032000** [klarna/electron-redux#279]
Hello. Sorry for asking, but I can't understand how to make and connect react between two windows. It just my first time, when I use Electron and it was so hard set-up webpack file for me, but after all I finally did it . I found your source, but I can't understand, how to divide my state and synchronize state between two windows. If someone has some code snippet or can do this, I will really appreciate it.

**Comment by hardchor** [comment]
Hey @Ruslan27032000! Take a look at our end-to-end tests for some good examples on how to set this up:
https://github.com/klarna/electron-redux/tree/master/packages/electron-redux-e2e/src
