### ISSUE TITLE
Use with redux-observable only triggers local epics

### ISSUE THREAD

**Issue by publicvirtualvoid** [klarna/electron-redux#304]
Using `electron-redux@2.0.0-alpha.8` and `redux-observable@1.2.0` in a fairly basic configuration.
I am not seeing epics defined in the main context triggered by actions dispatched by the renderer context, and vice-versa.
Is this expected behaviour? I was really hoping to handle context-dependent side-effects this way.
It's entirely possible I'm doing something silly, would someone be able to lend a hand?

Here's the main store:
```ts
const epicMiddleware = createEpicMiddleware();
export const store = configureStore({
  reducer: rootReducer,
  middleware: [epicMiddleware],
  enhancers: [stateSyncEnhancer()],
});

const testEpic = (action$: any) =>
  action$.pipe(
    tap((v) => {
      console.log('from main');
      console.log(v);
    }),
    ignoreElements()
  );
const rootEpic = combineEpics(testEpic);
epicMiddleware.run(rootEpic);
```
And the renderer (mostly identical):
```ts
const epicMiddleware = createEpicMiddleware();
export const store = configureStore({
  reducer: rootReducer,
  middleware: [epicMiddleware],
  enhancers: [stateSyncEnhancer()]
});

const testEpic = (action$: any) =>
  action$.pipe(
    tap((v) => {
      console.log('from renderer');
      console.log(v);
    }),
    ignoreElements()
  );
const rootEpic = combineEpics(testEpic);

epicMiddleware.run(rootEpic);
```

**Comment by matmalkowski** [comment]
It might be related to middleware & enhancer conflict -> can you try doing with with `composeWithStateSync` ([here is example](https://github.com/klarna/electron-redux/blob/2d05fa75231f06e74a7bd7276499061a589eaa73/tests/typescript/composeWithStateSync.ts#L15))

**Comment by publicvirtualvoid** [comment]
I've ended up with this after some fiddling. It's all running, but unfortunately the original problem persists.
```ts
export const mainStore = (() => {
  const epicMiddleware = createEpicMiddleware();
  const store = createStore(
    rootReducer,
    composeWithStateSync({})(applyMiddleware(epicMiddleware))
  );

  const testEpic = (action$: any) =>
    action$.pipe(
      tap((v) => {
        console.log('from main');
        console.log(v);
      }),
      ignoreElements()
    );
  const rootEpic = combineEpics(testEpic);

  epicMiddleware.run(rootEpic);
  return store;
})();
```

**Comment by matmalkowski** [comment]
Closing since its resolved now
